os: linux
  
language: go

go:
  - 1.13.x

services:
  - docker

script:   
  # Test the code
  - go test -v ./...
  # Build the code 
  - CGO_ENABLED=0 go build -o demo

  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t lukaswais/demo:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker login --username=lukaswais --password-stdin
  - docker tag lukaswais/demo:latest lukaswais/demo:$GIT_SHA
  - docker push lukaswais/demo:latest
  - docker push lukaswais/demo:$GIT_SHA
  

 